{"glance": [{"msg": "Artifact with a circular dependency can not be created", "code": 400, "name": "ArtifactCircularDependency"}, {"msg": "Artifact with the specified type, name and version already has the direct dependency=%(dep)s", "code": 409, "name": "ArtifactDuplicateDirectDependency"}, {"msg": "Artifact with the specified type, name and version already exists", "code": 409, "name": "ArtifactDuplicateNameTypeVersion"}, {"msg": "Artifact with the specified type, name and version already has the transitive dependency=%(dep)s", "code": 409, "name": "ArtifactDuplicateTransitiveDependency"}, {"msg": "Artifact with id=%(id)s is not accessible", "code": 403, "name": "ArtifactForbidden"}, {"msg": "Artifact has no property %(prop)s", "code": 400, "name": "ArtifactInvalidProperty"}, {"msg": "Cannot use this parameter with the operator %(op)s", "code": 400, "name": "ArtifactInvalidPropertyParameter"}, {"msg": "Artifact state cannot be changed from %(curr)s to %(to)s", "code": 400, "name": "ArtifactInvalidStateTransition"}, {"msg": "Cannot load artifact '%(name)s'", "code": "xxx", "name": "ArtifactLoadError"}, {"msg": "Plugin name '%(plugin)s' should match artifact typename '%(name)s'", "code": "xxx", "name": "ArtifactNonMatchingTypeName"}, {"msg": "Artifact with id=%(id)s was not found", "code": 404, "name": "ArtifactNotFound"}, {"msg": "No plugin for '%(name)s' has been loaded", "code": 404, "name": "ArtifactPluginNotFound"}, {"msg": "Property's %(prop)s value has not been found", "code": 404, "name": "ArtifactPropertyValueNotFound"}, {"msg": "Operator %(op)s is not supported", "code": 400, "name": "ArtifactUnsupportedPropertyOperator"}, {"msg": "Show level %(shl)s is not supported in this operation", "code": 400, "name": "ArtifactUnsupportedShowLevel"}, {"msg": "Connect error/bad request to Auth service at URL %(url)s.", "code": "xxx", "name": "AuthBadRequest"}, {"msg": "Auth service at URL %(url)s not found.", "code": "xxx", "name": "AuthUrlNotFound"}, {"msg": "Authorization failed.", "code": "xxx", "name": "AuthorizationFailure"}, {"msg": "Redirecting to %(uri)s for authorization.", "code": "xxx", "name": "AuthorizationRedirect"}, {"msg": "Incorrect auth strategy, expected \"%(expected)s\" but received \"%(received)s\"", "code": "xxx", "name": "BadAuthStrategy"}, {"msg": "Driver %(driver_name)s could not be configured correctly. Reason: %(reason)s", "code": "xxx", "name": "BadDriverConfiguration"}, {"msg": "Registry was not configured correctly on API server. Reason: %(reason)s", "code": "xxx", "name": "BadRegistryConnectionConfiguration"}, {"msg": "The Store URI was malformed.", "code": "xxx", "name": "BadStoreUri"}, {"msg": "Task was not configured properly", "code": "xxx", "name": "BadTaskConfiguration"}, {"msg": "There was an error configuring the client.", "code": "xxx", "name": "ClientConfigurationError"}, {"msg": "There was an error connecting to a server", "code": "xxx", "name": "ClientConnectionError"}, {"msg": "An object with the same identifier is currently being operated on.", "code": "xxx", "name": "Conflict"}, {"msg": "An object with the same identifier already exists.", "code": 409, "name": "Duplicate"}, {"msg": "The location %(location)s already exists", "code": 409, "name": "DuplicateLocation"}, {"msg": "You are not authorized to complete %(action)s action.", "code": 403, "name": "Forbidden"}, {"msg": "You are not authorized to complete this action.", "code": 403, "name": "ForbiddenPublicImage"}, {"msg": "An unknown exception occurred", "code": "xxx", "name": "GlanceException"}, {"msg": "The limit has been exceeded on the number of allowed image locations. Attempted: %(attempted)s, Maximum: %(maximum)s", "code": 413, "name": "ImageLocationLimitExceeded"}, {"msg": "The limit has been exceeded on the number of allowed image members for this image. Attempted: %(attempted)s, Maximum: %(maximum)s", "code": 413, "name": "ImageMemberLimitExceeded"}, {"msg": "Image with the given id %(image_id)s was not found", "code": 404, "name": "ImageNotFound"}, {"msg": "The limit has been exceeded on the number of allowed image properties. Attempted: %(attempted)s, Maximum: %(maximum)s", "code": 413, "name": "ImagePropertyLimitExceeded"}, {"msg": "The provided image is too large.", "code": 413, "name": "ImageSizeLimitExceeded"}, {"msg": "The limit has been exceeded on the number of allowed image tags. Attempted: %(attempted)s, Maximum: %(maximum)s", "code": 413, "name": "ImageTagLimitExceeded"}, {"msg": "An import task exception occurred", "code": 400, "name": "ImportTaskError"}, {"msg": "Data supplied was not valid.", "code": 400, "name": "Invalid"}, {"msg": "Property '%(name)s' may not have value '%(val)s': %(msg)s", "code": 400, "name": "InvalidArtifactPropertyValue"}, {"msg": "Artifact cannot change state from %(source)s to %(target)s", "code": 400, "name": "InvalidArtifactStateTransition"}, {"msg": "Invalid type definition", "code": 400, "name": "InvalidArtifactTypeDefinition"}, {"msg": "Invalid property definition", "code": 400, "name": "InvalidArtifactTypePropertyDefinition"}, {"msg": "Invalid content type %(content_type)s", "code": 415, "name": "InvalidContentType"}, {"msg": "Unable to filter using the specified operator.", "code": 400, "name": "InvalidFilterOperatorValue"}, {"msg": "Unable to filter using the specified range.", "code": 400, "name": "InvalidFilterRangeValue"}, {"msg": "Image status transition from %(cur_status)s to %(new_status)s is not allowed", "code": 400, "name": "InvalidImageStatusTransition"}, {"msg": "The provided body %(body)s is invalid under given schema: %(schema)s", "code": "xxx", "name": "InvalidJsonPatchBody"}, {"msg": "The provided path '%(path)s' is invalid: %(explanation)s", "code": "xxx", "name": "InvalidJsonPatchPath"}, {"msg": "Provided object does not match schema '%(schema)s': %(reason)s", "code": "xxx", "name": "InvalidObject"}, {"msg": "Invalid value for option %(option)s: %(value)s", "code": 400, "name": "InvalidOptionValue"}, {"msg": "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s", "code": 400, "name": "InvalidParameterValue"}, {"msg": "Invalid configuration in property protection file.", "code": 400, "name": "InvalidPropertyProtectionConfiguration"}, {"msg": "Received invalid HTTP redirect.", "code": "xxx", "name": "InvalidRedirect"}, {"msg": "Sort direction supplied was not valid.", "code": 400, "name": "InvalidSortDir"}, {"msg": "Sort key supplied was not valid.", "code": 400, "name": "InvalidSortKey"}, {"msg": "Invalid configuration in glance-swift conf file.", "code": 400, "name": "InvalidSwiftStoreConfiguration"}, {"msg": "Provided status of task is unsupported: %(status)s", "code": 400, "name": "InvalidTaskStatus"}, {"msg": "Status transition from %(cur_status)s to %(new_status)s is not allowed", "code": 400, "name": "InvalidTaskStatusTransition"}, {"msg": "Provided type of task is unsupported: %(type)s", "code": 400, "name": "InvalidTaskType"}, {"msg": "Version is invalid: %(reason)s", "code": 400, "name": "InvalidVersion"}, {"msg": "Invalid jsonpatch request", "code": "xxx", "name": "JsonPatchException"}, {"msg": "The request returned a 413 Request Entity Too Large. This generally means that rate limiting or a quota threshold was breached.\n\nThe response body:\n%(body)s", "code": 413, "name": "LimitExceeded"}, {"msg": "Maximum redirects (%(redirects)s) was exceeded.", "code": "xxx", "name": "MaxRedirectsExceeded"}, {"msg": "The metadata definition namespace=%(namespace_name)s already exists.", "code": 409, "name": "MetadefDuplicateNamespace"}, {"msg": "A metadata definition object with name=%(object_name)s already exists in namespace=%(namespace_name)s.", "code": 409, "name": "MetadefDuplicateObject"}, {"msg": "A metadata definition property with name=%(property_name)s already exists in namespace=%(namespace_name)s.", "code": 409, "name": "MetadefDuplicateProperty"}, {"msg": "A metadata definition resource-type with name=%(resource_type_name)s already exists.", "code": 409, "name": "MetadefDuplicateResourceType"}, {"msg": "The metadata definition resource-type association of resource-type=%(resource_type_name)s to namespace=%(namespace_name)s already exists.", "code": 409, "name": "MetadefDuplicateResourceTypeAssociation"}, {"msg": "A metadata tag with name=%(name)s already exists in namespace=%(namespace_name)s. (Please note that metadata tag names are case insensitive).", "code": 409, "name": "MetadefDuplicateTag"}, {"msg": "You are not authorized to complete this action.", "code": 403, "name": "MetadefForbidden"}, {"msg": "The metadata definition %(record_type)s with name=%(record_name)s not deleted. Other records still refer to it.", "code": 403, "name": "MetadefIntegrityError"}, {"msg": "Metadata definition namespace=%(namespace_name)s was not found.", "code": 404, "name": "MetadefNamespaceNotFound"}, {"msg": "The metadata definition object with name=%(object_name)s was not found in namespace=%(namespace_name)s.", "code": 404, "name": "MetadefObjectNotFound"}, {"msg": "The metadata definition property with name=%(property_name)s was not found in namespace=%(namespace_name)s.", "code": 404, "name": "MetadefPropertyNotFound"}, {"msg": "The metadata definition resource-type association of resource-type=%(resource_type_name)s to namespace=%(namespace_name)s, was not found.", "code": 404, "name": "MetadefResourceTypeAssociationNotFound"}, {"msg": "The metadata definition resource-type with name=%(resource_type_name)s, was not found.", "code": 404, "name": "MetadefResourceTypeNotFound"}, {"msg": "The metadata definition tag with name=%(name)s was not found in namespace=%(namespace_name)s.", "code": 404, "name": "MetadefTagNotFound"}, {"msg": "Missing required credential: %(required)s", "code": "xxx", "name": "MissingCredentialError"}, {"msg": "The request returned a 302 Multiple Choices. This generally means that you have not included a version indicator in a request URI.\n\nThe body of response returned:\n%(body)s", "code": "xxx", "name": "MultipleChoices"}, {"msg": "Response from Keystone does not contain a Glance endpoint.", "code": "xxx", "name": "NoServiceEndpoint"}, {"msg": "You are not authenticated.", "code": 401, "name": "NotAuthenticated"}, {"msg": "An object with the specified identifier was not found.", "code": 404, "name": "NotFound"}, {"msg": "Image %(image_id)s is protected and cannot be deleted.", "code": 403, "name": "ProtectedImageDelete"}, {"msg": "Metadata definition namespace %(namespace)s is protected and cannot be deleted.", "code": 403, "name": "ProtectedMetadefNamespaceDelete"}, {"msg": "Metadata definition property %(property_name)s is protected and cannot be deleted.", "code": 403, "name": "ProtectedMetadefNamespacePropDelete"}, {"msg": "Metadata definition object %(object_name)s is protected and cannot be deleted.", "code": 403, "name": "ProtectedMetadefObjectDelete"}, {"msg": "Metadata definition resource-type-association %(resource_type)s is protected and cannot be deleted.", "code": 403, "name": "ProtectedMetadefResourceTypeAssociationDelete"}, {"msg": "Metadata definition resource-type %(resource_type_name)s is a seeded-system type and cannot be deleted.", "code": 403, "name": "ProtectedMetadefResourceTypeSystemDelete"}, {"msg": "Metadata definition tag %(tag_name)s is protected and cannot be deleted.", "code": 403, "name": "ProtectedMetadefTagDelete"}, {"msg": "%(cls)s exception was raised in the last rpc call: %(val)s", "code": "xxx", "name": "RPCError"}, {"msg": "Attribute '%(property)s' is read-only.", "code": 403, "name": "ReadonlyProperty"}, {"msg": "Multiple 'image' service matches for region %(region)s. This generally means that a region is required and you have not supplied one.", "code": "xxx", "name": "RegionAmbiguity"}, {"msg": "Attribute '%(property)s' is reserved.", "code": 403, "name": "ReservedProperty"}, {"msg": "System SIGHUP signal received.", "code": "xxx", "name": "SIGHUPInterrupt"}, {"msg": "Unable to load schema: %(reason)s", "code": "xxx", "name": "SchemaLoadError"}, {"msg": "The request returned 500 Internal Server Error.", "code": "xxx", "name": "ServerError"}, {"msg": "The request returned 503 Service Unavailable. This generally occurs on service overload or other transient outage.", "code": "xxx", "name": "ServiceUnavailable"}, {"msg": "Unable to verify signature: %(reason)s", "code": "xxx", "name": "SignatureVerificationError"}, {"msg": "The size of the data %(image_size)s will exceed the limit. %(remaining)s bytes remaining.", "code": "xxx", "name": "StorageQuotaFull"}, {"msg": "An unknown task exception occurred", "code": "xxx", "name": "TaskException"}, {"msg": "Task with the given id %(task_id)s was not found", "code": 404, "name": "TaskNotFound"}, {"msg": "The request returned an unexpected status: %(status)s.\n\nThe response body:\n%(body)s", "code": "xxx", "name": "UnexpectedStatus"}, {"msg": "Artifact type with name '%(name)s' and version '%(version)s' is not known", "code": 404, "name": "UnknownArtifactType"}, {"msg": "Image upload problem: %s", "code": "xxx", "name": "UploadException"}, {"msg": "Server worker creation failed: %(reason)s.", "code": "xxx", "name": "WorkerCreationFailure"}]}